---
# defaults file for ansible-role-asciidoc-content-exporter
# User facing variables
work_dir: work                                   # Default work dir, represents the actual project when run in a container. Set to . if run outside a container
content_dir_name: content                        # Custom name for content dir
export_dir_name: dist                            # Custom name for export dir
themes_dir_name: themes                          # Custom name for themes dir
theme_name: custom                               # Default name for the custom theme to be used (SCSS name, without extension)
reveal_js_version: 3.8.0                         # Version of reveal.js to be used
include_banner: true                             # Adds an asciidocker banner for project support at the end of presentations/PDF
conditional_rebuild: never                       # How the monitoring of changes should be handled: git (via submodules status) or local (always rebuild)

# Internal variables - should not be changed                        
asciidoc_extension: .adoc                        # Default extension for asciidoc files
export_dir: "{{work_dir}}/{{export_dir_name}}"   # Where files will be exported, relative to project path 
content_dir: "{{work_dir}}/{{content_dir_name}}" # Local content directory. Usually an aggregation of submodules, relative to project path
themes_dir: "{{work_dir}}/{{themes_dir_name}}"   # Local themes directory (optional), relative to project path
