---
- name: "[PDF]: Clean {{export_dir}} folder"
  file:
    path: "{{export_dir}}/{{pdfs.key}}.pdf"
    state: absent
- name: "[PDF]: PDF Content export"
  # Note: Content dir here is relative to the location of the merged presentation. So we need to go back to the root of the project
  command: "{{export_dir}}/.bundle/.bin/asciidoctor-pdf {{item}} -D {{export_dir}}"
  with_items: "{{pdfs.value}}"