---
- name: "[PDF]: Check if custom css files exists"
  stat: 
    path: "{{sass_dir}}"
  register: themes
- name: "[PDF]: Remove {{pdfs.key}} in {{export_dir}} folder"
  file:
    path: "{{export_dir}}/{{pdfs.key}}"
    state: absent
- name: "[PDF]: Remove {{pdfs.key}}.ad in {{export_dir}} folder because of uncommitted changes"
  file:
    path: "{{export_dir}}/{{pdfs.key}}.ad"
    state: absent
  when: git_output.stdout_lines| list | length > 0

- name: "[PDF]: Check if merged document exists"
  stat:
    path: "{{export_dir}}/{{pdfs.key}}.ad"
  register: pdf_stat

- name: "[PDF]: Content aggregation"
  lineinfile: 
    dest: "{{export_dir}}/{{pdfs.key}}.ad"
    line: "{{lookup('file', item )}}"
    create: yes
  loop: "{{pdfs.value}}"
  when: pdf_stat.stat.exists == False

- name: "[PDF]: PDF Content export"
  # Note: Content dir here is relative to the location of the merged presentation. So we need to go back to the root of the project
  command: "{{export_dir}}/.bundle/.bin/asciidoctor-pdf {{export_dir}}/{{pdfs.key}}.ad -D {{export_dir}} -o {{pdfs.key}}"