---
- name: "[PRESENTATION]: Override theme_name if defined on presentation level. Defaults to {{theme_name}}"
  set_fact:
    theme_name: "{{presentations.value.theme | default(theme_name)}}"

- name: "[PRESENTATION]: Set theme_dir"
  set_fact:
    theme_dir: "{{themes_dir}}/{{theme_name}}"

- name: "[PRESENTATION]: Check if custom css files exists"
  stat: 
    path: "{{theme_dir}}"
  register: themes

- name: "[PRESENTATION]: Check if presentation exists"
  stat: 
    path: "{{export_dir}}/{{presentations.key}}"
  register: presentation_export_stat

- name: "[PRESENTATION]: Remove {{presentations.key}} in {{export_dir}} folder because of uncommitted changes"
  file:
    path: "{{export_dir}}/{{presentations.key}}"
    state: absent
  when: rebuild_item

- name: "[PRESENTATION]: Remove {{presentations.key}}{{asciidoc_extension}} in {{export_dir}} folder because of uncommitted changes"
  file:
    path: "{{export_dir}}/{{presentations.key}}{{asciidoc_extension}}"
    state: absent
  when: rebuild_item

- name: "[PRESENTATION]: Check if merged document exists"
  stat:
    path: "{{export_dir}}/{{presentations.key}}{{asciidoc_extension}}"
  register: presentation_stat
    
- name: "[PRESENTATION]: Content aggregation"
  lineinfile: 
    dest: "{{export_dir}}/{{presentations.key}}{{asciidoc_extension}}"
    line: "{{lookup('file', item )}}"
    create: yes
  loop: "{{presentations.value.content}}"
  when: presentation_stat.stat.exists == False

- name: "[PRESENTATION]: Add asciidocker support page"
  lineinfile: 
    dest: "{{export_dir}}/{{presentations.key}}{{asciidoc_extension}}"
    line: "{{lookup('file', 'banner.adoc' )}}"
    create: yes
  when: presentation_stat.stat.exists == False and include_banner

- name: "[PRESENTATION]: Copy {{theme_name}}.scss to reveal.js themes dir"
  copy:
      dest: "{{export_dir}}/reveal.js/css/theme/source/" 
      src: "{{theme_dir}}/" 
  when: themes.stat.exists == True 

- name: "[PRESENTATION]: Build custom theme"
  command: "node {{export_dir}}/node_modules/.bin/sass {{export_dir}}/reveal.js/css/theme/source/{{theme_name}}.scss {{export_dir}}/reveal.js/css/theme/{{theme_name}}.css"
  when: themes.stat.exists == True

- name: "[PRESENTATION]: HTML Content export"
  # Note: Content dir here is relative to the location of the merged presentation. So we need to go back to the root of the project
  command: "{{export_dir}}/.bundle/.bin/asciidoctor-revealjs -a content_dir=../{{content_dir_name}} {{export_dir}}/{{presentations.key}}{{asciidoc_extension}} -D {{export_dir}} -o {{presentations.key}}"
  when: rebuild_item or themes.stat.exists == True