---
# tasks file for ansible-role-asciidoc-content-exporter
- name: Check configuration is present
  stat:
    path: "{{work_dir}}/config.yml"
  register: config_stat
- name: Include configuration variables
  include_vars: "{{work_dir}}/config.yml"
  when: config_stat.stat.exists == True
- name: Copy sample configuration
  copy:
    dest: "{{work_dir}}" 
    src: config.yml.sample 
  when: config_stat.stat.exists == False
- fail:
    msg: "Cannot run the process: Configuration not found! Don't worry. A sample file config.yml.sample has been created! Remove the .sample and restart the export process."
  when: presentation is undefined or pdf is undefined
- include_tasks: install.yml
- name: "Check for local modifications ..."
  shell: "git submodule --quiet foreach git status -s --porcelain | awk -v var='{{content_dir}}/' '{print var $2}' "
  register: git_output
- include_tasks: build_presentation.yml
  loop: "{{ presentation|dict2items }}"
  loop_control: 
    loop_var: presentations
  when: presentation is defined
- include_tasks: build_pdf.yml
  loop: "{{ pdf|dict2items }}"
  loop_control: 
    loop_var: pdfs
  when: pdf is defined