---
# tasks file for ansible-role-asciidoc-content-exporter
- name: Include configuration variables
  include_vars: "{{work_dir}}/config.yml"
- fail:
    msg: Configuration not found! Make sure you have defined at least 1 collection (presentation or pdf)
  when: presentation is undefined or pdf is undefined
- include_tasks: install.yml
- name: "Check for local modifications ..."
  shell: "git submodule --quiet foreach git status -s --porcelain | awk -v var='{{content_dir}}/' '{print var $2}' "
  register: git_output
- include_tasks: build_presentation.yml
  loop: "{{ presentation|dict2items }}"
  loop_control: 
    loop_var: presentations
  when: presentation is defined
- include_tasks: build_pdf.yml
  loop: "{{ pdf|dict2items }}"
  loop_control: 
    loop_var: pdfs
  when: pdf is defined