---
# All default variables in role can be overriden. Uncomment and change if needed.
#content_dir_name: content                        # Custom name for content dir
#export_dir_name: dist                            # Custom name for export dir
#themes_dir_name: themes                          # Custom name for themes dir
#reveal_js_version: 3.8.0                         # Version of reveal.js to be used
#include_banner: true                             # Adds an asciidocker banner for project support at the end of presentations/PDF
#conditional_rebuild: never                       # How the monitoring of changes should be handled: git (via submodules status, experimental) or never (always rebuild)
# IMPORTANT: Be sure to include the content_dir variable in the relative path to your content!
presentation:                                     # Source content to include inside the rendered presentation. YAML list. 
  my-presentation.html:
    content:
      - "{{content_dir}}/module/title.adoc"
      - "{{content_dir}}/module/my-content.adoc"
pdf:                                              # Source content to include inside the rendered PDF. YAML list. If more than one entry content is aggregated.
  my-pdf-docuemt.pdf:
    content: 
      - "{{content_dir}}/module/my-content.adoc"